version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nextjs-test:latest
    container_name: nextjs-test-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (r) => {if (r.statusCode !== 200) process.exit(1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Development configuration (uncomment to use)
# services:
#   nextjs-dev:
#     image: node:20-alpine
#     container_name: nextjs-test-dev
#     working_dir: /app
#     volumes:
#       - .:/app
#       - /app/node_modules
#       - /app/.next
#     ports:
#       - "3000:3000"
#     environment:
#       - NODE_ENV=development
#     command: npm run dev